const NEWFEED_EXCHANGE_NAME = 'newfeed_exchange'
const NEWFEED_EXCHANGE_TYPE = 'topic'
const NEWFEED_EXCHANGE_QUEUE_NAME_PREFIX = 'newfeed_queue_'
const FOLLOWER_EXCHANGE_NAME = 'follower_exchange'
const FOLLOWER_EXCHANGE_TYPE = 'direct'
const FOLLOWER_EXCHANGE_QUEUE_NAME_PREFIX = 'follower_queue_'

module.exports ={
    NEWFEED_EXCHANGE_NAME,
    NEWFEED_EXCHANGE_TYPE,
    NEWFEED_EXCHANGE_QUEUE_NAME_PREFIX,
    FOLLOWER_EXCHANGE_NAME,
    FOLLOWER_EXCHANGE_TYPE,
    FOLLOWER_EXCHANGE_QUEUE_NAME_PREFIX
}