const NOTIFICATION_TYPE_NEW_COMMENT = 'new_comment_on_post'
const NOTIFICATION_TYPE_NEW_REQUEST_FRIEND = 'new_request_friend'
const NOTIFICATION_TYPE_ACCEPTED_FRIEND = 'accepted_friend'
const NOTIFICATION_TYPE_NEW_POST_REACTION = 'new_post_reaction'
const NOTIFICATION_TYPE_NEW_COMMENT_REACTION = 'new_comment_reaction'

const NOTIFICATION_TYPE = [
    NOTIFICATION_TYPE_ACCEPTED_FRIEND,
    NOTIFICATION_TYPE_NEW_COMMENT,
    NOTIFICATION_TYPE_NEW_POST_REACTION,
    NOTIFICATION_TYPE_NEW_REQUEST_FRIEND,
    NOTIFICATION_TYPE_NEW_COMMENT_REACTION
]


module.exports = {
    NOTIFICATION_TYPE_ACCEPTED_FRIEND,
    NOTIFICATION_TYPE_NEW_COMMENT,
    NOTIFICATION_TYPE_NEW_POST_REACTION,
    NOTIFICATION_TYPE_NEW_REQUEST_FRIEND,
    NOTIFICATION_TYPE_NEW_COMMENT_REACTION,
    NOTIFICATION_TYPE
}